title: Jiangyue Wang
logo: /assets/img/WJY-at-canopy.png
description: Jiangyue Wang is an enthusiatic researcher majoring in Ecology.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal