title: Jiangyue Wang
logo: /assets/img/WJY-at-canopy.png
description: Jiangyue Wang is an enthusiastic researcher majoring in Ecology.
show_downloads: false

plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole
